import turtle
import math

print("Welcome to Turtle Draw")

# User input
draw = str(input("Input something for the turtle to draw: ")).upper()
print(f"Will draw: {draw}")
size = int(input("Input the size of each character: "))
print(f"Character size: {size}")

# Variable setting
draw_chr = list(draw)
draw_ctr = len(draw)
ctr = 0
x = turtle.Turtle() # Initialize Turtle variable
x.shape("turtle") # Change Turtle shape

# Drawing Process
while ctr < draw_ctr:
    print(f"Currently drawing: {draw_chr[ctr]}")

    # Letters
    if draw_chr[ctr] == "A":
        x.left(90)
        x.forward(size/2)
        x.circle(-size/2, extent=180)
        x.right(90)
        x.forward(size)
        x.backward(size)
        x.left(90)
        x.forward(size/2)
        x.left(90)
        x.penup()
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "B":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size*0.75)
        x.circle(-size/4, extent=180)
        x.forward(size*0.75)
        x.left(180)
        x.forward(size*0.75)
        x.circle(-size/4, extent=180)
        x.forward(size*0.75)
        x.penup()
        x.left(180)
        x.forward(size+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "C":
        x.penup()
        x.forward(size)
        x.pendown()
        x.left(180)
        x.forward(size/2)
        x.circle(-size/2, extent=180)
        x.forward(size/2)
        x.right(90)
        x.penup()
        x.forward(size)
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "D":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size/2)
        x.circle(-size/2, extent=180)
        x.forward(size/2)
        x.penup()
        x.left(180)
        x.forward(size+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "E":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size)
        x.right(90)
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.right(90)
        x.forward(size)
        x.left(90)
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.left(90)
        x.forward(size)
        x.penup()
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "F":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size)
        x.right(90)
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.right(90)
        x.forward(size)
        x.left(90)
        x.penup()
        x.forward(size/2)
        x.left(90)
        x.forward(size+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "G":
        x.penup()
        x.forward(size)
        x.left(90)
        x.forward(size)
        x.left(90)
        x.forward(size/4)
        x.pendown()
        x.forward(size/4)
        x.circle(size/2, extent=270)
        x.left(90)
        x.forward(size/2)
        x.penup()
        x.left(90)
        x.forward(size/2)
        x.left(90)
        x.forward((size/2)+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "H":
        x.left(90)
        x.forward(size)
        x.left(180)
        x.forward(size/2)
        x.left(90)
        x.forward(size)
        x.right(90)
        x.penup()
        x.backward(size/2)
        x.pendown()
        x.forward(size)
        x.penup()
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "I":
        x.forward(size)
        x.backward(size/2)
        x.left(90)
        x.forward(size)
        x.left(90)
        x.forward(size/2)
        x.backward(size)
        x.forward(size/2)
        x.right(90)
        x.penup()
        x.backward(size)
        x.right(90)
        x.forward((size/2)+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "J":
        x.penup()
        x.left(90)
        x.forward(size)
        x.right(90)
        x.pendown()
        x.forward(size)
        x.right(90)
        x.forward(size/2)
        x.circle(-size/2, extent=180)
        x.right(90)
        x.penup()
        x.forward(size+(size*0.1))
        x.right(90)
        x.forward(size/2)
        x.left(90)
        x.pendown()
    elif draw_chr[ctr] == "K":
        x.left(90)
        x.forward(size)
        x.backward(size/2)
        x.right(90)
        x.forward(size/2)
        x.circle(size/2, extent=90)
        x.left(180)
        x.circle(-size/2, extent=90)
        x.left(180)
        x.circle(-size/2, extent=90)
        x.left(90)
        x.penup()
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "L":
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.backward(size)
        x.right(90)
        x.forward(size)
        x.penup()
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "M":
        x.left(90)
        x.forward(size/2)
        x.circle(-size/4, extent=180)
        x.forward(size/2)
        x.left(180)
        x.forward(size/2)
        x.circle(-size/4, extent=180)
        x.forward(size/2)
        x.penup()
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "N":
        x.left(90)
        x.forward(size/2)
        x.circle(-size/2, extent=180)
        x.forward(size/2)
        x.penup()
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "O":
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.circle(size/2)
        x.penup()
        x.forward((size/2)+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "P":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size*0.75)
        x.circle(-size/4, extent=180)
        x.forward(size*0.75)
        x.left(90)
        x.penup()
        x.forward(size/2)
        x.left(90)
        x.forward((size)+(size*0.1))
        x.pendown()
    elif draw_chr[ctr] == "Q":
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.circle(size/2)
        x.penup()
        x.left(90)
        x.forward(size/2)
        x.pendown()
        x.right(135)
        x.forward(size*0.75)
        x.penup()
        x.left(45)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "R":
        x.left(90)
        x.forward(size)
        x.right(90)
        x.forward(size*0.75)
        x.circle(-size/4, extent=180)
        x.forward(size*0.75)
        x.left(180)
        x.forward(size*0.75)
        x.circle(-size/4, extent=90)
        x.forward(size/4)
        x.penup()
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "S":
        x.forward(size/2)
        x.circle(size/4, extent=180)
        x.forward(size/4)
        x.circle(-size/4, extent=180)
        x.forward(size/2)
        x.right(90)
        x.penup()
        x.forward(size)
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "T":
        x.penup()
        x.forward(size/2)
        x.pendown()
        x.left(90)
        x.forward(size)
        x.right(90)
        x.backward(size/2)
        x.forward(size)
        x.penup()
        x.right(90)
        x.forward(size)
        x.left(90)
        x.forward(size*0.1)
        x.pendown()
    elif draw_chr[ctr] == "U":
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.left(180)
        x.forward(size/2)
        x.circle(size/2, extent=180)
        x.forward(size/2)
        x.penup()
        x.backward(size)
        x.right(90)
        x.forward(size*0.1)
        x.pendown()
    if draw_chr[ctr] == "V":
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.left(180)
        x.circle(size, extent=90)
        x.left(90)
        x.forward(size)
        x.penup()
        x.backward(size)
        x.right(90)
        x.forward(size*0.1)
        x.pendown()
    if draw_chr[ctr] == "W": # Make rounder
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.left(180)
        x.forward(size*0.75)
        x.circle(size/4, extent=180)
        x.forward(size*0.75)
        x.left(180)
        x.forward(size*0.75)
        x.circle(size/4, extent=180)
        x.forward(size*0.75)
        x.penup()
        x.backward(size)
        x.right(90)
        x.forward(size*0.1)
    if draw_chr[ctr] == "X":
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.left(180)
        x.circle(size/2, extent=180)
        x.left(180)
        x.penup()
        x.forward(size)
        x.left(180)
        x.pendown()
        x.circle(size/2, extent=180)
        x.left(90)
        x.penup()
        x.forward(size+(size*0.1))
        x.pendown()
    if draw_chr[ctr] == "Y":
        x.penup()
        x.left(90)
        x.forward(size)
        x.left(180)
        x.pendown()
        x.circle(size/2, extent=180)
        x.penup()
        x.left(90)
        x.forward(size/2)
        x.left(90)
        x.forward(size/2)
        x.pendown()
        x.forward(size/2)
        x.penup()
        x.left(90)
        x.forward((size/2)+(size*0.1))
        x.pendown()
    if draw_chr[ctr] == "Z":
        x.penup()
        x.left(90)
        x.forward(size)
        x.pendown()
        x.right(90)
        x.forward(size)
        x.left(45)
        x.backward(math.sqrt(size**2+size**2))
        x.right(45)
        x.forward(size)
        x.penup()
        x.forward(10)
        x.pendown()

    # Others
    elif draw_chr[ctr] == " ":
        x.penup()
        x.forward(size/2)
        x.pendown()
#   else:
#       print(f"Character {draw_chr[ctr]} is currently unavailable.")
    
    ctr += 1
turtle.done()