import turtle

print("Welcome to Turtle Draw")

# User Input
draw = str(input("Input something for the turtle to draw: ")).upper()
print(f"Will draw: {draw}")
size = int(input("Input the size of each character: "))
print(f"Character size: {size}")

# Variable Setting
draw_chr = list(draw)
draw_ctr = len(draw)
ctr = 0
x = turtle.Turtle()
x.shape("turtle") # Change Turtle Shape

# Drawing Process
while ctr < draw_ctr:
    print(f"Currently drawing: {draw_chr[ctr]}")

    # Letters
    if draw_chr[ctr] == "A":
        x.left(90)
        x.forward(25)
        x.circle(-25, extent=180)
        x.right(90)
        x.forward(50)
        x.backward(50)
        x.left(90)
        x.forward(25)
        x.left(90)
        x.penup()
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "B":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(30)
        x.circle(-10, extent=180)
        x.forward(30)
        x.left(180)
        x.forward(35)
        x.circle(-15, extent=180)
        x.forward(35)
        x.penup()
        x.left(180)
        x.forward(60)
        x.pendown()
    elif draw_chr[ctr] == "C":
        x.penup()
        x.forward(50)
        x.pendown()
        x.left(180)
        x.forward(25)
        x.circle(-25, extent=180)
        x.forward(25)
        x.right(90)
        x.penup()
        x.forward(50)
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "D":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(25)
        x.circle(-25, extent=180)
        x.forward(25)
        x.penup()
        x.left(180)
        x.forward(60)
        x.pendown()
    elif draw_chr[ctr] == "E":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(50)
        x.right(90)
        x.penup()
        x.forward(25)
        x.pendown()
        x.right(90)
        x.forward(50)
        x.left(90)
        x.penup()
        x.forward(25)
        x.pendown()
        x.left(90)
        x.forward(50)
        x.penup()
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "F":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(50)
        x.right(90)
        x.penup()
        x.forward(25)
        x.pendown()
        x.right(90)
        x.forward(50)
        x.left(90)
        x.penup()
        x.forward(25)
        x.left(90)
        x.forward(60)
        x.pendown()
    elif draw_chr[ctr] == "G":
        x.penup()
        x.forward(50)
        x.left(90)
        x.forward(50)
        x.left(90)
        x.forward(10)
        x.pendown()
        x.forward(15)
        x.circle(25, extent=270)
        x.left(90)
        x.forward(25)
        x.penup()
        x.left(90)
        x.forward(25)
        x.left(90)
        x.forward(35)
        x.pendown()
    elif draw_chr[ctr] == "H":
        x.left(90)
        x.forward(50)
        x.left(180)
        x.forward(25)
        x.left(90)
        x.forward(50)
        x.right(90)
        x.penup()
        x.backward(25)
        x.pendown()
        x.forward(50)
        x.penup()
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "I":
        x.forward(50)
        x.backward(25)
        x.left(90)
        x.forward(50)
        x.left(90)
        x.forward(25)
        x.backward(50)
        x.forward(25)
        x.right(90)
        x.penup()
        x.backward(50)
        x.right(90)
        x.forward(35)
        x.pendown()
    elif draw_chr[ctr] == "J":
        x.penup()
        x.left(90)
        x.forward(50)
        x.right(90)
        x.pendown()
        x.forward(50)
        x.right(90)
        x.forward(25)
        x.circle(-25, extent=180)
        x.right(90)
        x.penup()
        x.forward(60)
        x.right(90)
        x.forward(25)
        x.left(90)
        x.pendown()
    elif draw_chr[ctr] == "K":
        x.left(90)
        x.forward(50)
        x.backward(25)
        x.right(90)
        x.forward(25)
        x.circle(25, extent=90)
        x.left(180)
        x.circle(-25, extent=90)
        x.left(180)
        x.circle(-25, extent=90)
        x.left(90)
        x.penup()
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "L":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.backward(50)
        x.right(90)
        x.forward(50)
        x.penup()
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "M":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(25)
        x.right(90)
        x.forward(50)
        x.backward(50)
        x.left(90)
        x.forward(25)
        x.right(90)
        x.forward(50)
        x.penup()
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "N":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(50)
        x.right(90)
        x.forward(50)
        x.penup()
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "O":
        x.penup()
        x.forward(25)
        x.pendown()
        x.circle(25)
        x.penup()
        x.forward(35)
        x.pendown()
    elif draw_chr[ctr] == "P":
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(35)
        x.circle(-15, extent=180)
        x.forward(35)
        x.left(90)
        x.penup()
        x.forward(20)
        x.left(90)
        x.forward(60)
        x.pendown()
    elif draw_chr[ctr] == "Q":
        x.penup()
        x.forward(25)
        x.pendown()
        x.circle(25)
        x.penup()
        x.left(90)
        x.forward(25)
        x.pendown()
        x.right(135)
        x.forward(35)
        x.penup()
        x.left(45)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "R": # Try making the bottom part round
        x.left(90)
        x.forward(50)
        x.right(90)
        x.forward(35)
        x.circle(-15, extent=180)
        x.forward(35)
        x.backward(50)
        x.left(90)
        x.forward(20)
        x.penup()
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "S":
        x.forward(35)
        x.circle(15, extent=180)
        x.forward(25)
        x.circle(-10, extent=180)
        x.forward(40)
        x.right(90)
        x.penup()
        x.forward(50)
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "T":
        x.penup()
        x.forward(25)
        x.pendown()
        x.left(90)
        x.forward(50)
        x.right(90)
        x.backward(25)
        x.forward(50)
        x.penup()
        x.right(90)
        x.forward(50)
        x.left(90)
        x.forward(10)
        x.pendown()
    elif draw_chr[ctr] == "U":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.left(180)
        x.forward(25)
        x.circle(25, extent=180)
        x.forward(25)
        x.penup()
        x.backward(50)
        x.right(90)
        x.forward(10)
        x.pendown()
    if draw_chr[ctr] == "V":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.left(180)
        x.circle(50, extent=90)
        x.left(90)
        x.forward(25)
        x.penup()
        x.backward(50)
        x.right(90)
        x.forward(10)
        x.pendown()
    if draw_chr[ctr] == "W":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.backward(50)
        x.right(90)
        x.forward(25)
        x.left(90)
        x.forward(50)
        x.backward(50)
        x.right(90)
        x.forward(25)
        x.left(90)
        x.forward(50)
        x.backward(50)
        x.right(90)
        x.penup()
        x.forward(10)
        x.pendown()
    if draw_chr[ctr] == "X":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.left(180)
        x.circle(25, extent=180)
        x.left(180)
        x.penup()
        x.forward(50)
        x.left(180)
        x.pendown()
        x.circle(25, extent=180)
        x.left(90)
        x.penup()
        x.forward(60)
        x.pendown()
    if draw_chr[ctr] == "Y":
        x.penup()
        x.left(90)
        x.forward(50)
        x.left(180)
        x.pendown()
        x.circle(25, extent=180)
        x.penup()
        x.left(90)
        x.forward(25)
        x.left(90)
        x.forward(25)
        x.pendown()
        x.forward(25)
        x.penup()
        x.left(90)
        x.forward(35)
        x.pendown()
    if draw_chr[ctr] == "Z":
        x.penup()
        x.left(90)
        x.forward(50)
        x.pendown()
        x.right(90)
        x.forward(50)
        x.left(45)
        x.backward(70)
        x.right(45)
        x.forward(50)
        x.penup()
        x.forward(10)
        x.pendown()

    # Others
    elif draw_chr[ctr] == " ":
        x.penup()
        x.forward(20)
        x.pendown()
#   else:
#       print(f"Character {draw_chr[ctr]} is currently unavailable.")
    
    ctr += 1
turtle.done()